sudo: false
language: c
dist: xenial
env:
  global:
addons:
  apt:
    packages:
    - docbook-xsl
    - libbsd-dev
    - libedit-dev
    - libpam0g-dev
    - libperl-dev
    - libxml2-utils
    - python3
    - python3-dev
    - python3-minimal
    - tcl8.5
    - tcl8.5-dev
    - xsltproc
    - fonts-takao-mincho
    - fop
before_install:
  - scripts/before_install.sh
script:
  - scripts/install.sh
after_success:
  - if [ $TRAVIS_EVENT_TYPE = cron ]; then scripts/after_success.sh ; fi
  - if [ $TRAVIS_EVENT_TYPE = cron ]; then scripts/deploy.sh ; fi
branches:
  only:
    - master