baseURL = "https://noborus.github.io/"
author = "Noboru Saito"
paginate = 5
languageCode = "ja"
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
# Above are configs from hugoBasicExample

title = "Noboru Saito's page"
theme = "hugo-primer"
hasCJKLanguage = true
summaryLength = 140
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = "UA-136434199-2"
disqusShortname=""
copyright = "&copy;Noboru Saito 2019-2020"

[frontmatter]
# update sitemap.xml's lastmod datetime by file change time, instead of git.
# lastmod = ["lastmod", ":fileModTime", ":default"]

[params]
description = "Noboru Saito's site"
twitter = "noborus"
useIcon = true
useTwitterCard = true
# exampleSite must not have js share widget: #36
shareTo = ["Twitter", "Hatena", "Facebook", "Pocket"]
showFooterCredits = true
math = true
